# Generated by Django 5.0.3 on 2025-02-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
