# Generated by Django 5.0.3 on 2025-02-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps_Cliente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
