# Generated by Django 5.0.3 on 2025-02-11 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Apps_Admin', '0002_remove_doctor_email'),
        ('Apps_Cliente', '0002_delete_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps_Admin.hospital')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps_Admin.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
